# ruff: noqa: E501,I001
"""update

Revision ID: acfdc833e652
Revises: 024f9aac58e6
Create Date: 2025-10-14 20:58:07.391822

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'acfdc833e652'
down_revision = '024f9aac58e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_e164', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.add_column('users', sa.Column('risk_score', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('risk_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birth_year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_access_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone_e164'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'last_access_at')
    op.drop_column('users', 'birth_year')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'risk_updated_at')
    op.drop_column('users', 'risk_score')
    op.drop_column('users', 'role')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'phone_e164')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
